server:
  port: 8083
  tomcat:
    mbeanregistry:
      enabled: true

third.party:
  url: "http://localhost"
  port: "8080"

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    prometheus:
      enabled: true
