{
 "title": "Ktor",
 "time": { "from": "2022-01-12T15:59:47.305Z", "to": "2022-01-12T20:42:13.663Z" },
 "templating": {
  "list": [
   {
    "name": "frmwrk",
    "label": "framework",
    "query": "ktor-cio,ktor-netty,micronaut,spring,spring-reactive,mockserver,node,vertx"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Rate [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(ktor_http_server_requests_seconds_count{framework=~\"$frmwrk\", route=\"/\"}[1m]) ) by (framework)",
     "legendFormat": "{{framework}}"
    },
    {
     "expr": "sum (rate(http_server_requests_seconds_count{framework=~\"$frmwrk\", uri=~\"/|root\"}[1m]) ) by (framework)",
     "legendFormat": "{{framework}}"
    },
    {
     "expr": "sum (rate(http_request_duration_seconds_count{framework=~\"$frmwrk\", route=\"/\"}[1m]) ) by (framework)",
     "legendFormat": "{{framework}}"
    },
    {
     "expr": "sum (rate(vertx_http_server_requests_total{framework=~\"$frmwrk\", route=\"/\"}[1m]) ) by (framework)",
     "legendFormat": "{{framework}}"
    }
   ]
  },
  {
   "title": "Average Response Time [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(ktor_http_server_requests_seconds_sum{ framework=~\"$frmwrk\", route=\"/\", status = \"200\" }[1m]) / rate(ktor_http_server_requests_seconds_count{ framework=~\"$frmwrk\", route=\"/\", status = \"200\" }[1m])",
     "legendFormat": "{{framework}}"
    },
    {
     "expr": "avg((rate(http_server_requests_seconds_sum{ framework=~\"$frmwrk\", uri=~\"/|root\", status = \"200\" }[1m]) / rate(http_server_requests_seconds_count{ framework=~\"$frmwrk\", uri=~\"/|root\", status = \"200\" }[1m]))>0) by (framework, status)",
     "legendFormat": "{{framework}}"
    },
    {
     "expr": "rate(http_request_duration_seconds_sum{ framework=~\"$frmwrk\", route=\"/\" }[1m]) / rate(http_request_duration_seconds_count{ framework=~\"$frmwrk\", route=\"/\" }[1m])",
     "legendFormat": "{{framework}} "
    },
    {
     "expr": "rate(vertx_http_server_response_time_seconds_sum{ framework=~\"$frmwrk\", route=\"/\", code=\"200\" }[1m]) / rate(vertx_http_server_response_time_seconds_count{ framework=~\"$frmwrk\", route=\"/\", code=\"200\" }[1m])",
     "legendFormat": "{{framework}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{id =~ \"/docker/.*\", name=~\"$frmwrk\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum ( rate(container_cpu_usage_seconds_total{id =~ \"/docker/.*\", name=~\"$frmwrk\" } [1m]) ) by (name) ",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{framework=~\"$frmwrk\"}) by (area, framework)",
     "legendFormat": "{{framework}}-{{area}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{framework=~\"$frmwrk\"}",
     "legendFormat": "{{ framework }}-{{ state }}"
    }
   ]
  }
 ]
}