# prometheus.yml
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  scrape_timeout:      5s # Default value
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'performance-client-local'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'localhost:8082' ]
        labels:
          framework: ktor

  - job_name: 'performance-spring-local'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8084' ]
        labels:
          framework: spring

  - job_name: 'dsl-library-docker'
    metrics_path: '/metrics'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          framework: ktor

  - job_name: 'performance-client-docker'
    metrics_path: '/metrics'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: [ 'host.docker.internal:8082' ]
        labels:
          framework: ktor

  - job_name: 'performance-spring-docker'
    metrics_path: '/actuator/prometheus'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: [ 'host.docker.internal:8084' ]
        labels:
          framework: spring

  - job_name: 'docker'
    static_configs:
        - targets: ['host.docker.internal:9323']  # Docker monitoring
