global:
  scrape_interval: 5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  scrape_timeout: 5s # Default value
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'mockserver'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'mockserver1:8080','mockserver2:8080','mockserver3:8080' ]
        labels:
          framework: mockserver

  - job_name: 'ktor'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
        labels:
          framework: ktor

  - job_name: 'ktor-netty'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:8082' ]
        labels:
          framework: ktor-netty

  - job_name: 'ktor-tomcat'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:8085' ]
        labels:
          framework: ktor-tomcat

  - job_name: 'spring-reactive'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8083' ]
        labels:
          framework: spring-netty

  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8084' ]
        labels:
          framework: spring
